/*
 *
 * Profile constants
 *
 */

enum ActionTypes {
  DEFAULT_ACTION = 'app/Profile/DEFAULT_ACTION',
  CHANGE_PASSWORD_ACTION = 'app/Profile/CHANGE_PASSWORD_ACTION',
  CHANGE_PASSWORD_FAILED_ACTION = 'app/Profile/CHANGE_PASSWORD_FAILED_ACTION',
  CHANGING_PASSWORD_ACTION = 'app/Profile/CHANGING_PASSWORD_ACTION',
  CHANGED_PASSWORD_ACTION = 'app/Profile/CHANGED_PASSWORD_ACTION',
  CLEAR_CHANGE_PASSWORD_ERROR_ACTION = 'app/Profile/CLEAR_CHANGE_PASSWORD_ERROR_ACTION'
}

export default ActionTypes;
