enum ActionTypes {
  DEFAULT_ACTION = 'app/CreateReportPage/DEFAULT_ACTION',
  CREATE_REPORT_ACTION = 'app/CreateReportPage/CREATE_REPORT_ACTION',
  CREATE_REPORT_FAILED_ACTION = 'app/CreateReportPage/CREATE_REPORT_FAILED_ACTION',
  UPDATE_REPORT_TASK_ACTION = 'app/CreateReportPage/UPDATE_REPORT_TASK_ACTION',
  UPDATE_REPORT_TASK_FAILED_ACTION = 'app/CreateReportPage/UPDATE_REPORT_TASK_FAILED_ACTION',
  CREATE_REPORT_TASK_ACTION = 'app/CreateReportPage/CREATE_REPORT_TASK_ACTION',
  CREATE_REPORT_TASK_FAILED_ACTION = 'app/CreateReportPage/CREATE_REPORT_TASK_ACTION_FAILED',
  CLEAR_REPORT_TASK_CREATION_ERROR_ACTION = 'app/CreateReportPage/CLEAR_REPORT_TASK_CREATION_ERROR_ACTION',
  CLEAR_REPORT_TASK_UPDATE_ERROR_ACTION = 'app/CreateReportPage/CLEAR_REPORT_TASK_UPDATE_ERROR_ACTION'
}

export default ActionTypes;
