
enum ActionTypes {
  LOADING_ACTION = 'boilerplate/App/LOADING_ACTION',
  AUTH_ACTION_SUCCESS = 'boilerplate/App/AUTH_ACTION_SUCCESS',
  AUTH_ACTION_ERROR = 'boilerplate/App/AUTH_ACTION_ERROR',
  GET_ADMIN_REPORTS_SUCCESS = 'boilerplate/Home/GET_ADMIN_REPORTS_SUCCESS',
  GET_EMPLOYEE_PROFILE_SUCCESS = 'boilerplate/App/GET_EMPLOYEE_PROFILE_SUCCESS',
  GET_EMPLOYEES_SUCCESS = 'boilerplate/App/GET_EMPLOYEES_SUCCESS',
  GET_EMPLOYEE_REPORTS_SUCCESS = 'boilerplate/Home/GET_EMPLOYEE_REPORTS_SUCCESS',
  GET_EMPLOYEE_CUSTOMER_SUCCESS = 'boilerplate/Home/GET_EMPLOYEE_CUSTOMER_SUCCESS',
  GET_ALL_CUSTOMER_SUCCESS = 'boilerplate/Home/GET_ALL_CUSTOMER_SUCCESS',
  CREATE_REPORT_SUCCESS = 'app/CreateReportPage/CREATE_REPORT_SUCCESS',
  CREATE_REPORT_TASK_SUCCESS = 'app/CreateReportPage/CREATE_REPORT_TASK_SUCCESS',
  UPDATE_REPORT_TASK_SUCCESS = 'app/CreateReportPage/UPDATE_REPORT_TASK_SUCCESS',
  SUBMIT_REPORT_SUCCESS = 'app/CreateReportPage/SUBMIT_REPORT_SUCCESS',
  DELETE_REPORT_TASK_SUCCESS = 'app/CreateReportPage/DELETE_REPORT_TASK_SUCCESS',
  LOGOUT = 'boilerplate/App/LOGOUT',
}

export const JWT_SESSION_STORAGE_NAME = 'jwtToken';


export default ActionTypes;
